[
    {
        "agency": "Export-Import Bank of the United States",
        "description": "Ex-Im Bank provides a guarantee on working capital loans provided by commercial lenders to help extend short-term loans to small- and medium-size businesses for their export funding needs.  This resource includes information on eligibility and a list of participating lenders.",
        "gov_type": "Federal",
        "industry": null,
        "is_contractor": "1",
        "is_development": "1",
        "is_disabled": "1",
        "is_disaster": "1",
        "is_exporting": "1",
        "is_general_purpose": "1",
        "is_green": "1",
        "is_military": "1",
        "is_minority": "1",
        "is_rural": "1",
        "is_woman": "1",
        "loan_type": "Loan",
        "state_name": null,
        "title": "Working Capital Guarantee Program",
        "url": "http://www.exim.gov/products/work_cap.cfm"
    },
    {
        "agency": "National Oceanic and Atmospheric Administration (NOAA)",
        "description": "Provides long term financing for the cost of construction or reconstruction of fishing vessels, shoreline facilities, and aquacultural facilities.",
        "gov_type": "Federal",
        "industry": "Agriculture",
        "is_contractor": "0",
        "is_development": "0",
        "is_disabled": "0",
        "is_disaster": "0",
        "is_exporting": "0",
        "is_general_purpose": "0",
        "is_green": "0",
        "is_military": "0",
        "is_minority": "0",
        "is_rural": "0",
        "is_woman": "0",
        "loan_type": "Loan",
        "state_name": null,
        "title": "Fisheries Finance Program",
        "url": "http://www.nmfs.noaa.gov/mb/financial_services/ffp.htm"
    },
    {
        "agency": "Overseas Private Investment Corporation",
        "description": "For companies with annual revenues under $250,000, this program provides medium- to long-term funding through direct loans and loan guarantees to eligible investment projects in developing countries and emerging markets. ",
        "gov_type": "Federal",
        "industry": null,
        "is_contractor": "0",
        "is_development": "0",
        "is_disabled": "0",
        "is_disaster": "0",
        "is_exporting": "1",
        "is_general_purpose": "0",
        "is_green": "0",
        "is_military": "0",
        "is_minority": "0",
        "is_rural": "0",
        "is_woman": "0",
        "loan_type": "Loan",
        "state_name": null,
        "title": "Small and Medium Enterprise Financing Program",
        "url": "http://www.opic.gov/financing"
    },
    {
        "agency": "U.S. Dept of Agriculture",
        "description": "Makes and guarantees loans to approved socially disadvantaged applicants to buy and operate family-size farms and ranches.",
        "gov_type": "Federal",
        "industry": "Agriculture",
        "is_contractor": "0",
        "is_development": "0",
        "is_disabled": "0",
        "is_disaster": "0",
        "is_exporting": "0",
        "is_general_purpose": "0",
        "is_green": "0",
        "is_military": "0",
        "is_minority": "1",
        "is_rural": "0",
        "is_woman": "0",
        "loan_type": "Loan",
        "state_name": null,
        "title": "Socially Disadvantaged Farmers and Ranchers",
        "url": "http://www.fsa.usda.gov/FSA/webapp?area=home&subject=fmlp&topic=sfl"
    },
    {
        "agency": "U.S. Dept of Agriculture",
        "description": "Loans aimed at improving economic and environmental climate in rural communities. Funds may be used for buying a business to keep it from closing; purchasing land, buildings, machinery or equipment; and related activities.",
        "gov_type": "Federal",
        "industry": null,
        "is_contractor": "0",
        "is_development": "0",
        "is_disabled": "0",
        "is_disaster": "0",
        "is_exporting": "0",
        "is_general_purpose": "0",
        "is_green": "0",
        "is_military": "0",
        "is_minority": "0",
        "is_rural": "1",
        "is_woman": "0",
        "loan_type": "Loan",
        "state_name": null,
        "title": "Rural Business and Industry Guaranteed Loans",
        "url": "http://www.rurdev.usda.gov/rbs/busp/b&i_gar.htm"
    },
    {
        "agency": "U.S. Dept of Agriculture",
        "description": "Provides low-interest financing for producers to build or upgrade farm storage and handling facilities.",
        "gov_type": "Federal",
        "industry": "Agriculture",
        "is_contractor": "0",
        "is_development": "0",
        "is_disabled": "0",
        "is_disaster": "0",
        "is_exporting": "0",
        "is_general_purpose": "0",
        "is_green": "0",
        "is_military": "0",
        "is_minority": "0",
        "is_rural": "0",
        "is_woman": "0",
        "loan_type": "Loan",
        "state_name": null,
        "title": "Farm Storage Facility Loan Program",
        "url": "http://www.fsa.usda.gov/FSA/webapp?area=home&subject=prsu&topic=flp-fp"
    },
    {
        "agency": "U.S. Dept of Agriculture",
        "description": "Direct and guaranteed loans to beginning farmers and ranchers who are unable to obtain financing from commercial credit sources.",
        "gov_type": "Federal",
        "industry": "Agriculture",
        "is_contractor": "0",
        "is_development": "0",
        "is_disabled": "0",
        "is_disaster": "0",
        "is_exporting": "0",
        "is_general_purpose": "0",
        "is_green": "0",
        "is_military": "0",
        "is_minority": "0",
        "is_rural": "0",
        "is_woman": "0",
        "loan_type": "Loan",
        "state_name": null,
        "title": "Beginning Farms and Ranchers Loans",
        "url": "http://www.fsa.usda.gov/FSA/webapp?area=home&subject=fmlp&topic=bfl"
    },
    {
        "agency": "U.S. Dept of Agriculture",
        "description": "Loans to processors of domestically-produced sugarcane and sugar beets for the construction or upgrading of storage and handling facilities for raw sugars and refined sugars.",
        "gov_type": "Federal",
        "industry": "Agriculture",
        "is_contractor": "0",
        "is_development": "0",
        "is_disabled": "0",
        "is_disaster": "0",
        "is_exporting": "0",
        "is_general_purpose": "0",
        "is_green": "0",
        "is_military": "0",
        "is_minority": "0",
        "is_rural": "0",
        "is_woman": "0",
        "loan_type": "Loan",
        "state_name": null,
        "title": "Sugar Storage Facility Loan Program",
        "url": "http://www.fsa.usda.gov/FSA/webapp?area=home&subject=prsu&topic=flp-sp"
    },
    {
        "agency": "U.S. Dept of Agriculture",
        "description": "Loan programs for starting and operating farms and other agricultural businesses.",
        "gov_type": "Federal",
        "industry": "Agriculture",
        "is_contractor": "0",
        "is_development": "0",
        "is_disabled": "0",
        "is_disaster": "0",
        "is_exporting": "0",
        "is_general_purpose": "0",
        "is_green": "0",
        "is_military": "0",
        "is_minority": "0",
        "is_rural": "0",
        "is_woman": "0",
        "loan_type": "Loan",
        "state_name": null,
        "title": "Direct Farm Loans",
        "url": "http://www.fsa.usda.gov/FSA/webapp?area=home&subject=fmlp&topic=dfl"
    },
    {
        "agency": "U.S. Dept of Agriculture",
        "description": "Emergency loans to help producers recover from production and physical losses due to drought, flooding, other natural disasters, or quarantine.",
        "gov_type": "Federal",
        "industry": "Agriculture",
        "is_contractor": "0",
        "is_development": "0",
        "is_disabled": "0",
        "is_disaster": "1",
        "is_exporting": "0",
        "is_general_purpose": "0",
        "is_green": "0",
        "is_military": "0",
        "is_minority": "0",
        "is_rural": "0",
        "is_woman": "0",
        "loan_type": "Loan",
        "state_name": null,
        "title": "Emergency Farm Loans",
        "url": "http://www.fsa.usda.gov/FSA/webapp?area=home&subject=fmlp&topic=efl"
    },
    {
        "agency": "U.S. Dept of Agriculture",
        "description": "Commodity loan programs allow producers of designated crops to receive a loan from the government at a commodity-specific loan rate per unit of production by pledging production as loan collateral. After harvest, a farmer may obtain a loan for all or part of the new commodity production.",
        "gov_type": "Federal",
        "industry": "Agriculture",
        "is_contractor": "0",
        "is_development": "0",
        "is_disabled": "0",
        "is_disaster": "0",
        "is_exporting": "0",
        "is_general_purpose": "0",
        "is_green": "0",
        "is_military": "0",
        "is_minority": "0",
        "is_rural": "0",
        "is_woman": "0",
        "loan_type": "Loan",
        "state_name": null,
        "title": "Marketing Assistance Loan and LDP Programs",
        "url": "http://www.usda.gov/wps/portal/usda/!ut/p/c4/04_SB8K8xLLM9MSSzPy8xBz9CP0os_gAC9-wMJ8QY0MDpxBDA09nXw9DFxcXQ-cAA_2CbEdFAEUOjoE!/?navid=MARKETING_ASSISTANCE&edeployment_action=retrievecontent"
    },
    {
        "agency": "U.S. Dept of Agriculture",
        "description": "FSA guaranteed loans provide lenders with a guarantee of up to 95 percent of the loss of principal and interest on a loan. Farmers and ranchers apply to an agricultural lender, which then arranges for the guarantee.",
        "gov_type": "Federal",
        "industry": "Agriculture",
        "is_contractor": "0",
        "is_development": "0",
        "is_disabled": "0",
        "is_disaster": "0",
        "is_exporting": "0",
        "is_general_purpose": "0",
        "is_green": "0",
        "is_military": "0",
        "is_minority": "0",
        "is_rural": "0",
        "is_woman": "0",
        "loan_type": "Loan",
        "state_name": null,
        "title": "Guaranteed Farm Loans",
        "url": "http://www.fsa.usda.gov/FSA/webapp?area=home&subject=fmlp&topic=gfl"
    },
    {
        "agency": "U.S. Dept of the Interior",
        "description": "Financing for Indian-owned businesses that significantly contribute to a Tribe's economy.",
        "gov_type": "Federal",
        "industry": null,
        "is_contractor": "0",
        "is_development": "0",
        "is_disabled": "0",
        "is_disaster": "0",
        "is_exporting": "0",
        "is_general_purpose": "0",
        "is_green": "0",
        "is_military": "0",
        "is_minority": "1",
        "is_rural": "0",
        "is_woman": "0",
        "loan_type": "Loan",
        "state_name": null,
        "title": "Indian Loan Guaranty and Interest Subsidy Program",
        "url": "http://www.bia.gov/idc/groups/public/documents/text/idc-001933.pdf"
    },
    {
        "agency": "U.S. Small Business Administration",
        "description": "SBA's Export Working Capital Program (EWCP) loans are targeted for businesses that are able to generate export sales and need additional working capital to support these sales.",
        "gov_type": "Federal",
        "industry": null,
        "is_contractor": "0",
        "is_development": "0",
        "is_disabled": "0",
        "is_disaster": "0",
        "is_exporting": "1",
        "is_general_purpose": "0",
        "is_green": "0",
        "is_military": "0",
        "is_minority": "0",
        "is_rural": "0",
        "is_woman": "0",
        "loan_type": "Loan",
        "state_name": null,
        "title": "Export Working Capital",
        "url": "http://www.sba.gov/content/export-loan-programs#Export Working Capital Program (EWCP)"
    },
    {
        "agency": "U.S. Small Business Administration",
        "description": "The Community Adjustment and Investment Program (CAIP) was established to assist U.S. companies doing business in areas of the country that have been negatively affected by the North American Free Trade Agreement (NAFTA). CAIP loans allow for the payment of fees on eligible loans, including the 7(a) Loan Program guaranty fee and the 504 program guaranty and CDC and lender fees. Depending on the size of the loan, these fees can be sizeable. CAIP works with SBA to reduce borrower costs and increase the availability of these programs.",
        "gov_type": "Federal",
        "industry": null,
        "is_contractor": "0",
        "is_development": "1",
        "is_disabled": "0",
        "is_disaster": "0",
        "is_exporting": "0",
        "is_general_purpose": "1",
        "is_green": "0",
        "is_military": "0",
        "is_minority": "0",
        "is_rural": "0",
        "is_woman": "0",
        "loan_type": "Loan",
        "state_name": null,
        "title": " Community Adjustment and Investment Program (CAIP)",
        "url": "http://www.sba.gov/content/caip"
    },
    {
        "agency": "U.S. Small Business Administration",
        "description": "Provides very small loans to start-up, newly established, or growing small business concerns. SBA makes funds available to nonprofit community based lenders which, in turn, make loans to eligible borrowers in amounts up to a maximum of $35,000. Applications are submitted to the local intermediary and all credit decisions are made on the local level. ",
        "gov_type": "Federal",
        "industry": "Child Care",
        "is_contractor": "0",
        "is_development": "1",
        "is_disabled": "0",
        "is_disaster": "0",
        "is_exporting": "0",
        "is_general_purpose": "1",
        "is_green": "0",
        "is_military": "0",
        "is_minority": "0",
        "is_rural": "0",
        "is_woman": "0",
        "loan_type": "Loan",
        "state_name": null,
        "title": "Microloan Program",
        "url": "http://www.sba.gov/content/microloan-program"
    },
    {
        "agency": "U.S. Small Business Administration",
        "description": "Any business or private, nonprofit organization that is located in a declared disaster area and has incurred damage during the disaster may apply for a loan to help replace damaged property or restore it to the condition it was in before the disaster. If your business or private, nonprofit organization - large or small - has suffered physical damage as a result of a disaster, you may be eligible for financial assistance from the U.S. Small Business Administration. SBA makes physical disaster loans of up to $2 million to qualified businesses or private, nonprofit organizations.",
        "gov_type": "Federal",
        "industry": null,
        "is_contractor": "0",
        "is_development": "0",
        "is_disabled": "0",
        "is_disaster": "1",
        "is_exporting": "0",
        "is_general_purpose": "0",
        "is_green": "0",
        "is_military": "0",
        "is_minority": "0",
        "is_rural": "0",
        "is_woman": "0",
        "loan_type": "Loan",
        "state_name": null,
        "title": "Business Physical Disaster Loans",
        "url": "http://www.sba.gov/content/business-physical-disaster-loans"
    },
    {
        "agency": "U.S. Small Business Administration",
        "description": "Small business owenrs and entrepreneurs don't  always need large loans.  The  Advantage programs help business owners get crucial small loans (under $250,000) with a streamlined application, minimal paperwork, and fast turnaround times, while still offering SBA's highest guarantee. These funds are available to financial institutions for the purpose of extending credit to small businesses.",
        "gov_type": "Federal",
        "industry": null,
        "is_contractor": "0",
        "is_development": "0",
        "is_disabled": "0",
        "is_disaster": "0",
        "is_exporting": "0",
        "is_general_purpose": "1",
        "is_green": "0",
        "is_military": "0",
        "is_minority": "0",
        "is_rural": "0",
        "is_woman": "0",
        "loan_type": "Loan",
        "state_name": null,
        "title": "SBA Preferred Lender Program",
        "url": "http://www.sba.gov/advantage"
    },
    {
        "agency": "U.S. Small Business Administration",
        "description": "CAPLines is the umbrella program under which the SBA helps small businesses meet their short-term and cyclical working-capital needs.",
        "gov_type": "Federal",
        "industry": null,
        "is_contractor": "0",
        "is_development": "1",
        "is_disabled": "0",
        "is_disaster": "0",
        "is_exporting": "0",
        "is_general_purpose": "1",
        "is_green": "0",
        "is_military": "0",
        "is_minority": "0",
        "is_rural": "0",
        "is_woman": "0",
        "loan_type": "Loan",
        "state_name": null,
        "title": "CAPLines",
        "url": "http://www.sba.gov/content/caplines"
    },
    {
        "agency": "U.S. Small Business Administration",
        "description": "The CDC/504 loan program is a long-term financing tool for economic development within a community. The 504 Program provides growing businesses with long-term, fixed-rate financing for major fixed assets, such as land and buildings.",
        "gov_type": "Federal",
        "industry": null,
        "is_contractor": "0",
        "is_development": "1",
        "is_disabled": "0",
        "is_disaster": "0",
        "is_exporting": "0",
        "is_general_purpose": "0",
        "is_green": "0",
        "is_military": "0",
        "is_minority": "0",
        "is_rural": "0",
        "is_woman": "0",
        "loan_type": "Loan",
        "state_name": null,
        "title": "Certified Development Company (CDC) 504 Loan Program",
        "url": "http://www.sba.gov/content/cdc504-loan-program"
    },
    {
        "agency": "U.S. Small Business Administration",
        "description": "The SBA Export Express program provides exporters and lenders a streamlined method to obtain SBA backed financing for loans and lines of credit up to $500,000. Lenders use their own credit decision process and loan documentation; exporters get access to their funds faster. The SBA provides an expedited eligibility review and provides a response in 36 hours or less. To learn more, contact your local district office. ",
        "gov_type": "Federal",
        "industry": null,
        "is_contractor": "0",
        "is_development": "0",
        "is_disabled": "0",
        "is_disaster": "0",
        "is_exporting": "1",
        "is_general_purpose": "0",
        "is_green": "0",
        "is_military": "0",
        "is_minority": "0",
        "is_rural": "0",
        "is_woman": "0",
        "loan_type": "Loan",
        "state_name": null,
        "title": "Export Express",
        "url": "http://www.sba.gov/content/export-loan-programs#Export Express Program"
    },
    {
        "agency": "U.S. Small Business Administration",
        "description": "The Employee Trusts program is designed to provide financial assistance to Employee Stock Ownership Plans.  The SBA can assist qualified employee trusts that meet the requirements and conditions for an Employee Stock Ownership Plan (ESOP) as prescribed in all applicable IRS, Treasury, and Department of Labor regulations. Your small business must provide all the funds needed to collaterize and repay the loan.",
        "gov_type": "Federal",
        "industry": null,
        "is_contractor": "0",
        "is_development": "1",
        "is_disabled": "0",
        "is_disaster": "0",
        "is_exporting": "0",
        "is_general_purpose": "0",
        "is_green": "0",
        "is_military": "0",
        "is_minority": "0",
        "is_rural": "0",
        "is_woman": "0",
        "loan_type": "Loan",
        "state_name": null,
        "title": "Employee Trusts",
        "url": "http://www.sba.gov/content/employee-trusts"
    },
    {
        "agency": "U.S. Small Business Administration",
        "description": "The Military Reservist Economic Injury Disaster Loan program (MREIDL) provides funds to help an eligible small business meet ordinary and necessary operating expenses that it could have met, but is unable to meet, because an essential employee was called-up to active duty in their role as a military reservist.",
        "gov_type": "Federal",
        "industry": null,
        "is_contractor": "0",
        "is_development": "0",
        "is_disabled": "0",
        "is_disaster": "0",
        "is_exporting": "0",
        "is_general_purpose": "1",
        "is_green": "0",
        "is_military": "0",
        "is_minority": "0",
        "is_rural": "0",
        "is_woman": "0",
        "loan_type": "Loan",
        "state_name": null,
        "title": "Military Reservists Economic Injury Loans",
        "url": "http://www.sba.gov/content/military-reservists-economic-injury-loans"
    },
    {
        "agency": "U.S. Small Business Administration",
        "description": "Small businesses, small agricultural cooperatives and certain private, non-profit organizations of all sizes that have suffered substantial economic injury resulting from a physical disaster or an agricultural production disaster designated by the Secretary of Agriculture may be eligible for the SBA's Economic Injury Disaster Loan Program.",
        "gov_type": "Federal",
        "industry": null,
        "is_contractor": "0",
        "is_development": "0",
        "is_disabled": "0",
        "is_disaster": "1",
        "is_exporting": "0",
        "is_general_purpose": "0",
        "is_green": "0",
        "is_military": "0",
        "is_minority": "0",
        "is_rural": "0",
        "is_woman": "0",
        "loan_type": "Loan",
        "state_name": null,
        "title": "Economic Injury Loans",
        "url": "http://www.sba.gov/content/economic-injury-disaster-loans"
    },
    {
        "agency": "U.S. Small Business Administration",
        "description": "Small business owenrs and entrepreneurs don't  always need large loans.  The Advantage programs help business owners get crucial small loans (under $250,000) with a streamlined application, minimal paperwork, and fast turnaround times, while still offering SBA's highest guarantee. These funds are available to financial institutions for the purpose of extending credit to small businesses.",
        "gov_type": "Federal",
        "industry": null,
        "is_contractor": "0",
        "is_development": "0",
        "is_disabled": "0",
        "is_disaster": "0",
        "is_exporting": "0",
        "is_general_purpose": "1",
        "is_green": "0",
        "is_military": "0",
        "is_minority": "0",
        "is_rural": "0",
        "is_woman": "0",
        "loan_type": "Loan",
        "state_name": null,
        "title": "Mission-Focused Lenders",
        "url": "http://www.sba.gov/advantage"
    },
    {
        "agency": "U.S. Small Business Administration",
        "description": "Provides financing to eligible small businesses for the planning, design, or installation of a pollution control facility.  ** Note: Pollution Control loans are not being dispersed at this time.  Please check back for updates.",
        "gov_type": "Federal",
        "industry": "Environmental Management",
        "is_contractor": "0",
        "is_development": "0",
        "is_disabled": "0",
        "is_disaster": "0",
        "is_exporting": "0",
        "is_general_purpose": "0",
        "is_green": "1",
        "is_military": "0",
        "is_minority": "0",
        "is_rural": "0",
        "is_woman": "0",
        "loan_type": "Loan",
        "state_name": null,
        "title": "Pollution Control Loans",
        "url": "http://www.sba.gov/content/pollution-control"
    },
    {
        "agency": "U.S. Small Business Administration",
        "description": "Small business owners and entrepreneurs don’t always need large loans.  The Community Advantage and Small Loan Advantage programs help business owners get crucial smaller loans (under $250,000) with a streamlined application, minimal paperwork and fast turnaround times, while still offering SBA’s highest guarantee.",
        "gov_type": "Federal",
        "industry": null,
        "is_contractor": "0",
        "is_development": "0",
        "is_disabled": "0",
        "is_disaster": "0",
        "is_exporting": "0",
        "is_general_purpose": "1",
        "is_green": "0",
        "is_military": "0",
        "is_minority": "0",
        "is_rural": "0",
        "is_woman": "0",
        "loan_type": "Loan",
        "state_name": null,
        "title": "Small Loan Advantage",
        "url": "http://www.sba.gov/advantage"
    },
    {
        "agency": "U.S. Small Business Administration",
        "description": "The SBA International Trade Loan program is a term loan designed for businesses that plan to start/continue exporting or those that that have been adversely affected by competition from imports. The proceeds of the loan must enable the borrower to be in a better position to compete.",
        "gov_type": "Federal",
        "industry": null,
        "is_contractor": "0",
        "is_development": "0",
        "is_disabled": "0",
        "is_disaster": "0",
        "is_exporting": "1",
        "is_general_purpose": "0",
        "is_green": "0",
        "is_military": "0",
        "is_minority": "0",
        "is_rural": "0",
        "is_woman": "0",
        "loan_type": "Loan",
        "state_name": null,
        "title": "International Trade Loans",
        "url": "http://www.sba.gov/content/export-loan-programs#International Trade Loan Program"
    },
    {
        "agency": "U.S. Small Business Administration",
        "description": "Provides financial assistance for veterans and members of the military community wanting to establish or expand small businesses.  To learn more, contact your local district office. ",
        "gov_type": "Federal",
        "industry": null,
        "is_contractor": "0",
        "is_development": "0",
        "is_disabled": "0",
        "is_disaster": "0",
        "is_exporting": "0",
        "is_general_purpose": "0",
        "is_green": "0",
        "is_military": "1",
        "is_minority": "0",
        "is_rural": "0",
        "is_woman": "0",
        "loan_type": "Loan",
        "state_name": null,
        "title": "Patriot Express Pilot Loan Initiative",
        "url": "http://www.sba.gov/content/express-programs"
    },
    {
        "agency": "U.S. Small Business Administration",
        "description": "If you are in a declared disaster area and are the victim of a disaster, you may be eligible for financial assistance from the U.S. Small Business Administration - even if you don't own a business. As a homeowner, renter and/or personal-property owner, you may apply to the SBA for a loan to help you recover from a disaster.",
        "gov_type": "Federal",
        "industry": null,
        "is_contractor": "0",
        "is_development": "0",
        "is_disabled": "0",
        "is_disaster": "1",
        "is_exporting": "0",
        "is_general_purpose": "0",
        "is_green": "0",
        "is_military": "0",
        "is_minority": "0",
        "is_rural": "0",
        "is_woman": "0",
        "loan_type": "Loan",
        "state_name": null,
        "title": "Disaster Assistance Loans",
        "url": "http://www.sba.gov/category/navigation-structure/loans-grants/small-business-loans/disaster-loans"
    },
    {
        "agency": "U.S. Small Business Administration",
        "description": "If you are in a declared disaster area and are the victim of a disaster, you may be eligible for financial assistance from the U.S. Small Business Administration - even if you don't own a business. As a homeowner, renter and/or personal-property owner, you may apply to the SBA for a loan to help you recover from a disaster.",
        "gov_type": "Federal",
        "industry": null,
        "is_contractor": "0",
        "is_development": "0",
        "is_disabled": "0",
        "is_disaster": "1",
        "is_exporting": "0",
        "is_general_purpose": "0",
        "is_green": "0",
        "is_military": "0",
        "is_minority": "0",
        "is_rural": "0",
        "is_woman": "0",
        "loan_type": "Loan",
        "state_name": null,
        "title": "Home and Personal Property Loans",
        "url": "http://www.sba.gov/content/home-and-personal-property-loans"
    },
    {
        "agency": "U.S. Small Business Administration",
        "description": "Small business owners and entrepreneurs don't  always need large loans.  The Community Advantage and Small Loan Advantage programs help business owners get crucial small loans (under $250,000) with a streamlined application, minimal paperwork, and fast turnaround times, while still offering SBA's highest guarantee. These funds are available to financial institutions for the purpose of extending credit to small businesses.",
        "gov_type": "Federal",
        "industry": null,
        "is_contractor": "0",
        "is_development": "0",
        "is_disabled": "0",
        "is_disaster": "0",
        "is_exporting": "0",
        "is_general_purpose": "1",
        "is_green": "0",
        "is_military": "0",
        "is_minority": "0",
        "is_rural": "0",
        "is_woman": "0",
        "loan_type": "Loan",
        "state_name": null,
        "title": "Community Advantage",
        "url": "http://www.sba.gov/advantage"
    },
    {
        "agency": "U.S. Small Business Administration",
        "description": "Community Express is an SBA pilot, 7(a) loan program for small businesses in low and moderate income areas.  Lenders are not required to take collateral for loans up to $25,000. Lenders may use their existing collateral policy for loans over $25,000 up to $250,000. To learn more, contact your local district office. ",
        "gov_type": "Federal",
        "industry": null,
        "is_contractor": "0",
        "is_development": "0",
        "is_disabled": "0",
        "is_disaster": "0",
        "is_exporting": "0",
        "is_general_purpose": "1",
        "is_green": "0",
        "is_military": "0",
        "is_minority": "0",
        "is_rural": "0",
        "is_woman": "0",
        "loan_type": "Loan",
        "state_name": "Alabama",
        "title": "Community Express",
        "url": "http://www.sba.gov/content/express-programs"
    },
    {
        "agency": "U.S. Small Business Administration",
        "description": "For starting, acquiring and expanding a small business, 7(a) loans are the most basic and most used type loan of SBA's business loan programs. Borrowers must apply through a participating lender institution.",
        "gov_type": "Federal",
        "industry": null,
        "is_contractor": "0",
        "is_development": "1",
        "is_disabled": "0",
        "is_disaster": "0",
        "is_exporting": "0",
        "is_general_purpose": "1",
        "is_green": "0",
        "is_military": "0",
        "is_minority": "0",
        "is_rural": "0",
        "is_woman": "0",
        "loan_type": "Loan",
        "state_name": null,
        "title": "Basic 7(a) Loan Program",
        "url": "http://www.sba.gov/category/navigation-structure/loans-grants/small-business-loans/sba-loan-programs/7a-loan-program"
    },
    {
        "agency": "U.S. Small Business Administration",
        "description": "SBICs are privately owned and managed investment funds, licensed and regulated by SBA, that use their own capital plus funds borrowed with an SBA guarantee to make equity and debt investments in qualifying small businesses.",
        "gov_type": "Federal",
        "industry": null,
        "is_contractor": "0",
        "is_development": "0",
        "is_disabled": "0",
        "is_disaster": "0",
        "is_exporting": "0",
        "is_general_purpose": "1",
        "is_green": "0",
        "is_military": "0",
        "is_minority": "0",
        "is_rural": "0",
        "is_woman": "0",
        "loan_type": "Venture Capital",
        "state_name": null,
        "title": "Small Business Investment Company (SBIC) Financing ",
        "url": "http://www.sba.gov/content/sbic-program-0"
    },
    {
        "agency": "U.S. Small Business Administration",
        "description": "A developmental venture capital program designed to promote economic development and the creation of wealth and job opportunities in low-income geographic areas and among individuals living in such areas.",
        "gov_type": "Federal",
        "industry": null,
        "is_contractor": "0",
        "is_development": "1",
        "is_disabled": "0",
        "is_disaster": "0",
        "is_exporting": "0",
        "is_general_purpose": "1",
        "is_green": "0",
        "is_military": "0",
        "is_minority": "0",
        "is_rural": "0",
        "is_woman": "0",
        "loan_type": "Venture Capital",
        "state_name": null,
        "title": "New Markets Venture Capital",
        "url": "http://www.sba.gov/content/new-markets-venture-capital-companies"
    },
    {
        "agency": "Department of Housing and Urban Development",
        "description": "The Single Room Occupancy (SRO) Program provides rental assistance for applicable properties that will—when the renovations are complete contain upgraded single occupancy units for individuals who are homeless. ",
        "gov_type": "Federal",
        "industry": null,
        "is_contractor": "0",
        "is_development": "0",
        "is_disabled": "0",
        "is_disaster": "0",
        "is_exporting": "0",
        "is_general_purpose": "1",
        "is_green": "0",
        "is_military": "0",
        "is_minority": "0",
        "is_rural": "0",
        "is_woman": "0",
        "loan_type": "Grant",
        "state_name": null,
        "title": "Single-Room Occupancy (SRO) Program",
        "url": "http://www.hudhre.info/index.cfm?do=viewSroProgram"
    },
    {
        "agency": "Department of Housing and Urban Development",
        "description": "It is designed to promote, grants under the Supportive Housing Program are awarded through a national competition held annually, as part of a local Continuum of Care strategy, the development of supportive housing and supportive services to assist homeless persons in the transition from homelessness and to enable them to live as independently as possible.",
        "gov_type": "Federal",
        "industry": null,
        "is_contractor": "0",
        "is_development": "0",
        "is_disabled": "0",
        "is_disaster": "0",
        "is_exporting": "0",
        "is_general_purpose": "1",
        "is_green": "0",
        "is_military": "0",
        "is_minority": "0",
        "is_rural": "0",
        "is_woman": "0",
        "loan_type": "Grant",
        "state_name": null,
        "title": "Supportive Housing Program",
        "url": "http://www.hud.gov/offices/cpd/homeless/programs/shp/"
    },
    {
        "agency": "Department of Justice",
        "description": "Grants made under this grant program support programs that provide assistance to victims of domestic violence, dating violence, sexual assault, and stalking who are in need of transitional housing, short-term housing assistance, and related support services, including counseling, support groups, safety planning, and advocacy services as well as practical services such as licensed child care, employment services, transportation vouchers, telephones, and referrals to other agencies. ",
        "gov_type": "Federal",
        "industry": null,
        "is_contractor": "0",
        "is_development": "0",
        "is_disabled": "0",
        "is_disaster": "0",
        "is_exporting": "0",
        "is_general_purpose": "1",
        "is_green": "0",
        "is_military": "0",
        "is_minority": "0",
        "is_rural": "0",
        "is_woman": "0",
        "loan_type": "Grant",
        "state_name": null,
        "title": "Transitional Housing Assistance Program",
        "url": "http://www.ovw.usdoj.gov/thousing_grant_desc.htm"
    },
    {
        "agency": "Department of Justice",
        "description": "The primary purpose of the Rural Program is to enhance the safety of children, youth, and adults who are victims of domestic violence, dating violence, sexual assault, and stalking by supporting projects uniquely designed to address and prevent these crimes in rural jurisdictions.    Eligible applicants are States, Indian tribes, local governments, and nonprofit, public, or private entities, including tribal nonprofit organizations and faith-based or community organizations. ",
        "gov_type": "Federal",
        "industry": null,
        "is_contractor": "0",
        "is_development": "0",
        "is_disabled": "0",
        "is_disaster": "0",
        "is_exporting": "0",
        "is_general_purpose": "0",
        "is_green": "0",
        "is_military": "0",
        "is_minority": "0",
        "is_rural": "1",
        "is_woman": "0",
        "loan_type": "Grant",
        "state_name": null,
        "title": "Rural Grant Program",
        "url": "http://www.ovw.usdoj.gov/rural_grant_desc.htm"
    },
    {
        "agency": "Department of Justice",
        "description": "Disability Grant Program recipients will provide training, consultation, and information on domestic violence, dating violence, stalking, and sexual assault against individuals with disabilities and enhance direct services to such individuals.  By statute, eligible applicants include states; units of local government; Indian tribal governments or tribal organizations; and non profit and non-governmental victim services organizations, such as a state domestic violence or sexual assault coalitions or nonprofit, nongovernmental organization serving disabled individuals.",
        "gov_type": "Federal",
        "industry": null,
        "is_contractor": "0",
        "is_development": "0",
        "is_disabled": "0",
        "is_disaster": "0",
        "is_exporting": "0",
        "is_general_purpose": "1",
        "is_green": "0",
        "is_military": "0",
        "is_minority": "0",
        "is_rural": "0",
        "is_woman": "0",
        "loan_type": "Grant",
        "state_name": null,
        "title": "Disability Grant Program",
        "url": " http://www.ovw.usdoj.gov/WomenwithDisabilitiesBrief2002.htm"
    },
    {
        "agency": "Department of Veteran Affairs",
        "description": "The purpose of the Grant and Per Diem Program is to fund community agencies providing services to homeless Veterans.  ",
        "gov_type": "Federal",
        "industry": null,
        "is_contractor": "0",
        "is_development": "0",
        "is_disabled": "0",
        "is_disaster": "0",
        "is_exporting": "0",
        "is_general_purpose": "1",
        "is_green": "0",
        "is_military": "0",
        "is_minority": "0",
        "is_rural": "0",
        "is_woman": "0",
        "loan_type": "Grant",
        "state_name": null,
        "title": "Homeless Providers Grant and Per Diem Program",
        "url": "http://www.va.gov/HOMELESS/GPD.asp"
    },
    {
        "agency": "U.S. Small Business Administration",
        "description": "These two programs award a specific percentage of Federal R&D funds to qualified small businesses. SBIR/STTR programs encourage small firms to undertake scientific research that helps meet Federal R&D objectives, and have high potential for commercialization if successful.",
        "gov_type": "Federal",
        "industry": "Technology",
        "is_contractor": "1",
        "is_development": "0",
        "is_disabled": "0",
        "is_disaster": "0",
        "is_exporting": "0",
        "is_general_purpose": "1",
        "is_green": "0",
        "is_military": "0",
        "is_minority": "0",
        "is_rural": "0",
        "is_woman": "0",
        "loan_type": "Grant",
        "state_name": null,
        "title": "Small Business Innovation Research (SBIR) Program & Small Business Technology Transfer (STTR)",
        "url": "http://www.sba.gov/about-sba-services/7050"
    }
]